### ISSUE TITLE
Need to update bokeh-specific code in PyTplot

### ISSUE THREAD

**Issue by jibarnum** [MAVENSDC/PyTplot#107]
When trying to plot in bokeh, you get the below error and nothing plots.

bokeh.util.warnings.BokehDeprecationWarning: CoffeeScript support is deprecated and will be removed in an eventual 2.0 release. Use JavaScript or TypeScript directly instead.

**Comment by bryan-harter** [comment]
I believe I have figured this out by converting all of our coffeescript to typescript
