### ISSUE TITLE
Distinguish coordinates and dimensions for multidimensional data

### ISSUE THREAD

**Issue by amanotk** [MAVENSDC/PyTplot#109]
I have experienced a problem when loading 3D distribution functions with mms_load_fpi in pyspedas.
The loaded tplot variable does not have v1 and v3 coordinates which are ignored in trying to set the coordiantes in sotre_data because exceptions raised are simply ignored. This is also causing a problem when you try to apply pyspedas.time_clip to the variable.

The issue seems to arise because xarray's dimension and coordinate can have the same name only if the coordinate is 1D. I am relatively new to xarray but doing some experiments found that you can set multidimensional coordinates if dimension and coordinate names are different.

My suggestion is to use different names for dimensions such as v1_dim, v2_dim, etc.
I guess this is better than using different coordinate names because the coordinates are referenced in many places with like `.coords['v1']`, whereas dimensions (like `.v1` attributes) are not.

If this fix is fine, I can send a pull request.
I confirmed time_clip is working with it.

**Comment by bryan-harter** [comment]
Sorry about the delay on this, and thanks for explaining it more at AGU.  I believe I fixed it, there was actually two problems:

1) The dimension and coordinate names can't be the same, so the dimensions are now just labeled "v1_dim", "v2_dim", etc as you suggested

2) If v1/v3 actually vary in time (as v3 does in MMS FPI dist data), then it wouldn't have stored properly anyway.  

So now when you load in MMS FPI data, you should be able to access the coordinate v3 with the attribute "pytplot.data_quants['mms_dis_dist_data'].coords['v3']" , and you should see that it varies over both "time" and "v3_dim".    

In the future, it would be nice to add the ability to specify dimension names, perhaps read out of the CDF files.  I'll add a ticket.  

Let me know if the latest version works for you, and I'll close this issue.

**Comment by amanotk** [comment]
I have confirmed that the latest version works fine for me for FPI/MMS burst mode.
Thank you for your effort.
