### ISSUE TITLE
Create a function that calculates the power spectrum

### ISSUE THREAD

**Issue by esalvolucas** [MAVENSDC/PyTplot#11]
Okay I've actually worked through some of the details on this one. Here is how it is done in IDL: dpwrspec.pro

You have a 1D line TVar. You allow the user to specify 2 numbers, nboxpoints and nshiftpoints. They default to 256 and 128 respectively, so that's what I use the rest of this algorithm. But remember you can allow the user to select these.

So you take the first 256 data points, both x (time) and y (the data).

Recalculate y by subtracting the best linear fit of those 256 points, i.e. :

x = x - x[0]
c = np.polyfit(x, y, 1)
y_trend = c[0]*x + c[1]
y = y - y_trend

Then, calculate the "window" (I don't really know what this means) with:

w = scipy.signal.get_window("hanning", 256)

Then calculate the power spectrum of those 256 points:

f,pxx = scipy.signal.periodogram(y[0:256], window=w, detrend=lambda x : x)

Now, shift 128 points over, and do this again for the next 256 points, i.e. points number 128 to 384. And then shift 128 points again, and again, etc, until you are out of points to look at.

Then this data should be read into pytplot, where f is the spec bins, all of the different "pxx" are the data that fill out each column, and the times are at x[128], x[256], x[384], etc. So this will generate a multi-column dataframe from a dataframe that is just one column.

There is also some stuff with binning at the end of the function in IDL. Basically, it looks like a user can set a "bin_size" option, and average each column by bin_size at a time.

For example, if bin_size is 3, and there are 15 columns, then it averages together columns [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]. This makes a total of only 5 columns.
As an option:

-Allow users to select whether or not to subtract out the average fit line
-Average out each row of data to compress all the columns into one
-Not use the hanning window (just set window=None in the periodogram function)

**Comment by bryan-harter** [comment]
This was the same thing as another ticket
