### ISSUE TITLE
tplot_math.tinterp is adding the whole data structure to tplot_names()

### ISSUE THREAD

**Issue by ilgingell** [MAVENSDC/PyTplot#119]
Lines 35 and 42 both add `new_tvar2` to the name attribute of the tplot variable with these two lines: 

```    
pytplot.data_quants[tvar2].name = new_tvar2
pytplot.data_quants[tvar1 + '_tinterp'].name = new_tvar2
```

but `new_tvar2` is the whole structure with name, attributes, and the data quantities. So it ends up putting xarrays into the list of tplot_names which breaks a few other bits and pieces.

This seemed to fix it, though I don't know if its the best way:

```   
pytplot.data_quants[tvar2].name = copy.deepcopy(new_tvar2.name)
pytplot.data_quants[tvar1 + '_tinterp'].name = copy.deepcopy(new_tvar2.name)
```

**Comment by MAVENSDC** [comment]
Thanks for catching that!  The latest version should fix it.
