### ISSUE TITLE
legend_name options for tplot variables interprets string as list of strings

### ISSUE THREAD

**Issue by phansel** [MAVENSDC/PyTplot#130]
For any given tplot variable with a single line, options(tplot_name, "legend_names", "abcd") will erroneously convert string "abcd" into a list ['a','b','c','d'] and use a, b, c, and d as the legend names. 

This typically also results in the following error:

`Number of lines do not match length of legend names`

To label the plot correctly, one has to write options(tplot_name, "legend_names", ["abcd"]).

For option values that can be lists of one, options() should be modified to correctly accept both lists and single strings.

**Comment by phansel** [comment]
This appears to also be the case for any string option: ytitle, xtitle, ztitle, etc.

**Comment by phansel** [comment]
Either [this line](https://github.com/MAVENSDC/PyTplot/blob/master/pytplot/options.py#L100) is not working, or I'm on an old version of pytplot.

**Comment by supervised** [comment]
Thanks for the report! This one should be fixed in #137
