### ISSUE TITLE
Axis titles cannot be wrapped or extended onto multiple lines

### ISSUE THREAD

**Issue by phansel** [MAVENSDC/PyTplot#132]
Axis titles in PyTplot cannot be wrapped (i.e. overflowed) onto multiple lines, apparently since PyQtGraph has no such support for text wrapping. A search through their documentation showed zero results for "text wrap" or anything relating to overflow.

Label wrapping (manually, via adding a line breaking "\" in the label) is a standard feature of Tplot - is there any hope of this being supported in pytplot?

**Comment by bryan-harter** [comment]
I just pushed up a change that will allow the / character to start a new line in the labels.  These is one issue with it... each line does not automatically center.  For whatever reason, only the largest line becomes centered, and the other lines are flushed to the left.  I think ultimately this can be fixed, but it would require basically inheriting classes from pyqtgraph.

However, in the meantime, one can do a decent job of manually centering the text by adding spaces in the name in an attempt to align each row individually.  Here was the example I was working with:

![image](https://user-images.githubusercontent.com/41062454/106210402-f42afc80-6183-11eb-94b1-e61e26c20022.png)

**Comment by phansel** [comment]
If I remember correctly, the '\' character was used as a delimiter since it doesn't conflict with usage for fractions.

**Comment by bryan-harter** [comment]
Ah whoops, I actually did program it for '\', I just made a typo above
