### ISSUE TITLE
Y-axis labels are way too far from the plots, with no obvious way to adjust distance

### ISSUE THREAD

**Issue by phansel** [MAVENSDC/PyTplot#133]
Y-axis labels, configured by `pytplot.options("var_name", "ytitle", "Y Axis Variable")`, cannot be moved closer to plots. 

There are around 90 pixels of whitespace by default between the axis labels and the actual plot edge. This is an unreasonable default:

![axislabel](https://user-images.githubusercontent.com/15009257/104112462-2c45ca80-52bd-11eb-9e1d-867e83f4469b.png)

**Comment by phansel** [comment]
You can also see, on the colorbar, that there's some extremely weird behavior going on with the z-axis label units.

(keV/(....keV)) (x1e+06) `pyqtgraph.AxisItem.enableAutoSIPrefix(enable=False)` should be asserted [somewhere in here](https://github.com/MAVENSDC/PyTplot/blob/master/pytplot/QtPlotter/CustomAxis/AxisItem.py). 

I can't even find a place where units are provided to pyqtgraph. Why is the z-axis arbitrarily centered on 1?

**Comment by bryan-harter** [comment]
For the first issue, that latest version of pyqtgraph should now bring in the y axis labels closer: 
![image](https://user-images.githubusercontent.com/41062454/107096441-04685a80-67c8-11eb-9bb2-94b3fb7378fc.png)

Before this latest pytplot version, every plot had 100px of white space to the left of the plot, which ensured that all plots would line up correctly.  However, I just made changes to determine the best width for each plot to the left of the y-axis, and then set the rest of the plots to that number of pixels.

**Comment by phansel** [comment]
Looks great!
