### ISSUE TITLE
Issues at spectrogram bin boundaries

### ISSUE THREAD

**Issue by supervised** [MAVENSDC/PyTplot#145]
I received a bug report showing that the boundaries for spectrogram bins don't seem to match the boundaries in IDL spectrograms; I think the bin definitions are treated differently in 2 ways:

1) the values specified in 'v' seem to be bin boundaries, not bin centers (in IDL, they're treated as bin centers)

2) the bin boundaries at the min/max seem to always extend to the min/max of the y-axis (i.e., probably because of (1), the top and bottom bins extend to the edge of the figure)

Here's a simple example:

```
from pytplot import store_data, tplot, options
import numpy as np

data = np.array([[0,       1,       2,       3,       4],
       [5,       6,       7,       8,       9],
      [10,      11,      12,      13,      14],
      [15,      16,      17,      18,      19],
      [20,      21,      22,      23,      24]])

store_data('bins_1', data={'x': [1, 2, 3, 4, 5], 'y': data.transpose(), 'v': [10, 20, 30, 40, 50]})

options('bins_1', 'spec', 1)
options('bins_1', 'yrange', [0, 60.0])
options('bins_1', 'Colormap', 'jet')
tplot('bins_1')
```

![pytplot_bins_1](https://user-images.githubusercontent.com/4745136/124967399-39781380-dfd9-11eb-909e-e552f1b9d6a4.png)

Note: if you change the yrange to [-10, 70] the top and bottom bins will extend to [-10, 70]. 

The IDL figure looks like this:

```
mms_init

data = indgen(5, 5)

store_data, 'bins_1', data={x: [1, 2, 3, 4, 5], y: data, v: [10, 20, 30, 40, 50]}

options, 'bins_1', 'spec', 1
options, 'bins_1', 'yrange', [0, 60.0]
tplot, 'bins_1'
```

![idl_bins_1](https://user-images.githubusercontent.com/4745136/124967603-747a4700-dfd9-11eb-8796-096d0f1201db.png)

Is there a way to update pytplot to use the 'v' values as bin centers instead of edges?

**Comment by bryan-harter** [comment]
This one should also be fixed on the latest version of master

**Comment by supervised** [comment]
Thanks!
