### ISSUE TITLE
Interpolation options for spectrograms

### ISSUE THREAD

**Issue by ericthewizard** [MAVENSDC/PyTplot#146]
In IDL SPEDAS, we have interpolation options for spectrogram figures:

**no_interp**: if set to 0, interpolates along the x, and y axes
**x_no_interp**: if set to 0, interpolates along the x-axis
**y_no_interp**: if set to 0, interpolates along the y-axis

Is it possible to add something like this to pyTplot?

Here are some examples from IDL:

(1) Normal figure
![normal](https://user-images.githubusercontent.com/4745136/124970003-40ecec00-dfdc-11eb-833c-0f3ef38d1390.png)

(2) y_no_interp=0
![y_no_interp](https://user-images.githubusercontent.com/4745136/124970035-49ddbd80-dfdc-11eb-9de0-84091cbb63b8.png)

(3) x_no_interp=0
![x_no_interp](https://user-images.githubusercontent.com/4745136/124970057-4ea27180-dfdc-11eb-96a6-0a08ca041a48.png)

(4) no_interp=0
![no_interp](https://user-images.githubusercontent.com/4745136/124970076-53ffbc00-dfdc-11eb-8232-c958fdcf92a7.png)

**Comment by jameswilburlewis** [comment]
This has been available for quite a while in the pytplot-mpl-temp package, except that the sense of the options is flipped:

```
    def test_themis_peef_bins_interp_both(self):
        del_data("*")
        themis.esa(probe='a',trange=['2016-12-11','2016-12-12'])
        timespan('2016-12-11',1,'hours')
        options('tha_peef_en_eflux','yrange', [1000,3000])
        options('tha_peef_en_eflux', 'x_interp',1)
        options('tha_peef_en_eflux', 'x_interp_points', 500)
        options('tha_peef_en_eflux', 'y_interp',1)
        options('tha_peef_en_eflux', 'y_interp_points', 200)
        tplot_options('title', 'Interpolated along both x and y axes')
        tplot('tha_peef_en_eflux',save_png='tha_peef_en_eflux_interp_both',display=global_display)

```
