### ISSUE TITLE
axis_font_size doesn't work

### ISSUE THREAD

**Issue by supervised** [MAVENSDC/PyTplot#149]
Setting the 'axis_font_size' option doesn't seem to do anything. Here's an example:

```
import pyspedas
pyspedas.omni.data(trange=['2015-10-01','2015-11-01'])
from pytplot import tplot_options
tplot_options('axis_font_size', 25)
tplot('BZ_GSE')
```

**Comment by bryan-harter** [comment]
Thanks for catching that, looks like the way to change to axis font changed in one of the newer versions of pyqtgraph.  The new master branch should fix that

**Comment by supervised** [comment]
Thanks!
