### ISSUE TITLE
Plotting a spectrum-type variable takes a much longer time than before

### ISSUE THREAD

**Issue by horit** [MAVENSDC/PyTplot#155]
With pytplot 1.7.28 and pyspedas 1.2.8, still I can plot a spectrum-type tplot variable with tplot, while it takes quite a long (~1 min) time for a plot window to show up, if the tplot variable contains a time series "v" array (e.g., (times, 32)). You can plot almost in no time if a spectrum-type variable has a fixed v array (e.g., (32 )). 
I am sure that it did not take that long before (e.g., with pytplot 1.7.24). I guess this problem could be caused by some changes that have been made for the code between the two versions. It would be appreciated if you would kindly look into this. Thanks! 

P.S. I tested the above on Python 3.9.6 on macOS 10.14.6 with pytplot 1.7.28 and pyspedas 1.2.8.

**Comment by jameswilburlewis** [comment]
In the matplotlib-backend branch, we've made several changes to the specplot algorithms, and made better use of numpy tools.  The CPU time and memory  usage for specplots should be much better in pytplot-mpl-temp 2.2.32 and later.  Please let us know if you find a case that's still too slow, or if plots are not rendered correctly.
