### ISSUE TITLE
Deprecation warnings in cdf_to_tplot.py

### ISSUE THREAD

**Issue by sapols** [MAVENSDC/PyTplot#161]
I was writing some code today and noticed that numpy is yelling at pytplot because you're using a deprecated function. The warning message explains exactly how to correct it:

> /root/venv/lib/python3.7/site-packages/pytplot/importers/cdf_to_tplot.py:201: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  `delta_plus_var = delta_plus_var.astype(float)*np.float(si_conv.split('>')[0])`

The warning is duplicated for `delta_minus_var` as well:

> /root/venv/lib/python3.7/site-packages/pytplot/importers/cdf_to_tplot.py:213: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  `delta_minus_var = delta_minus_var.astype(float)*np.float(si_conv.split('>')[0])`

**Comment by supervised** [comment]
Thanks for reporting this! Should be fixed in the `matplotlib-backend` branch (and the latest `pytplot-mpl-temp` in PyPI release).
