### ISSUE TITLE
pytplot.options color error message needs specifics

### ISSUE THREAD

**Issue by sapols** [MAVENSDC/PyTplot#166]
I was trying to color a plot while using `pytplot-mpl-temp`:
```
pytplot.options('mms1_fgm_b_gsm_brst_l2-despike', 'color', 'blue')
```
But I kept getting a blank plot with the error message: `Problem with the number of line colors specified`

I finally found [this comment in a pySPEDAS issue](https://github.com/spedas/pyspedas/issues/168#issuecomment-1165738066) suggesting I reformat the colors like:
```
pytplot.options('mms1_fgm_b_gsm_brst_l2-despike', 'Color', ['purple', 'green', 'red', 'black'])
```

That fixed things. But it's next to impossible for a normal person to figure out what the problem is from the vague message `Problem with the number of line colors specified`. I noticed the error arrises if I don't supply an array of colors with exactly the same length as the number of variables being plotted. Somewhere in the code must realize there are four variables and therefore four colors are needed; simply adding the number of expected colors would go a _long_ way.

**Comment by supervised** [comment]
Thanks, updated!

**Comment by sapols** [comment]
Hey perfect! Thanks for the lightning fast turnaround on this Eric.
