### ISSUE TITLE
store_data cannot be used to set metadata only

### ISSUE THREAD

**Issue by jameswilburlewis** [MAVENSDC/PyTplot#175]
store_data issues an error and exits without doing anything, if an attr_dict argument is passed, but no data or newname.   In this case, if the specified variable name is already in pytplot, it should update attr_dict.

**Comment by ericthewizard** [comment]
I agree that this should work, but it's worth noting that if you returned the metadata from a loaded tplot variable and edited it, it's already updated in memory (due to get/get_data returning a reference to the metadata in memory, and not a copy), e.g., 


```
m = get('mms1_fgm_b_gsm_srvy_l2_bvec', metadata=True)
m['data_att']['item'] = 'value'
m2 = get('mms1_fgm_b_gsm_srvy_l2_bvec', metadata=True)
m2['data_att']
```

> {'coord_sys': 'GSM', 'y_units': None, 'z_units': None, 'item': 'value'}

**Comment by jameswilburlewis** [comment]
Closed for now -- I have added a `replace_metadata()` routine for metadata-only updates, similar to replace_data.  We may want to revisit this issue at some point, because IDL users are likely to be surprised if calling `pytplot.store_data()` to alter the data values also resets all the metadata, as currently happens now.  On the other hand, there may be value in distinguishing creation of a brand-new variable from updating an existing variable...
