### ISSUE TITLE
Compute Plasma Moment

### ISSUE THREAD

**Issue by esalvolucas** [MAVENSDC/PyTplot#25]
The SPEDAS paper said one of the biggest things that should be converted to python is the plasma moment computation. I've tried looking into it, and I can barely understand what is going on without looking into it more.

Check out the appendix here for moment computation:

https://lasp.colorado.edu/maven/sdc/public/pages/datasets/SISs/maven_sis_SWIA-r1_3.pdf

**Comment by bryan-harter** [comment]
More information on Plasma Moments

https://wsx.lanl.gov/RSX/PPSS_2006/lectures/Simakov_LANL_PPSS07.pdf

Chapter 6 of this: 

http://www.issibern.ch/PDF-Files/analysis_methods_1_1a.pdf


In general it looks like if you take the integral of the distribution function w.r.t velocity, you'll get the zeroth moment, which is the number density.  If you take the integral of the distribution function * velocity w.r.t. velocity, you'll get the bulk velocity vector.
