### ISSUE TITLE
tplot_math fixes

### ISSUE THREAD

**Issue by bryan-harter** [MAVENSDC/PyTplot#38]
- I just took a slightly closer look at the code, is flatten in a spot where it is working yet?

- In full flatten and several other functions, you do something like:

`df = pytplot.data_quants[tvars[0]].data`

But the problem with that is that modifying "df" now affects the original Tvars data too.  This is because dataframes don't create a copy by default, you'd need to write 

`df = pytplot.data_quants[tvars[0]].data.copy()`

In order to get a brand new one.

- Also, throughout all functions, spec_bins seems neglected, but spec_bins can actually be time varying too.  It should be read back in to the new tplot variable with the store_data command.

**Comment by bryan-harter** [comment]
For that last bullet point, as an example:

```
def full_flatten(tvar1,new_tvar):
    df = pytplot.data_quants[tvar1].data.copy()
    df_index = list(df.columns)
    #divide by column average
    for i in df_index:
        df[i] = df[i]/df[i].mean()
    
    if pytplot.data_quants[tvar1].spec_bins is None:
        pytplot.store_data(new_tvar,data = {'x':df.index,'y':df})
    else:
        pytplot.store_data(new_tvar,data = {'x':df.index,'y':df, 'v':pytplot.data_quants[tvar1].spec_bins})
    return 
```

This will read back in the original spec_bins too

**Comment by esalvolucas** [comment]
Note to self: make everything (crop, fn_interp, etc) work with spec bins IF spec bins exists AND >1 row

(x:time, y:data, v:specbins)

**Comment by esalvolucas** [comment]
Also note to self:

Fix interp nan by specifying how many seconds of NaNs to interpolate over (#nans = user input seconds/variable cadence)
