### ISSUE TITLE
Change up the date axis with pyqtgraph

### ISSUE THREAD

**Issue by bryan-harter** [MAVENSDC/PyTplot#41]
If you have more than a day's worth of data, pyqtgraph only shows the day of the month on the time axis.  It should be changed to show hh:mm:ss for much longer, perhaps only switching over after ~15-20 days.  

Additionally, it would be great if we could ensure that new dates would always show up as YYYY-MM-DD.  I suspect that might involve quite a bit of digging into the pg.AxisItem we are inheriting.  

The code to be modified resides in pytplot/QtPlotter/CustomAxis/DateAxis.py

**Comment by jibarnum** [comment]
Hah, @bryan-harter you would be correct that this is taking a bit to dig through the pg.AxisItem code to figure out how to make new dates always show up....

**Comment by bryan-harter** [comment]
This issue will be fixed upon the latest merge
