### ISSUE TITLE
Add the ability to change the x axis label

### ISSUE THREAD

**Issue by bryan-harter** [MAVENSDC/PyTplot#45]
This should probably be an option in tplot_options.  Need to make sure it works with both bokeh and pyqtgraph.  With bokeh, we would just need to add something like " self.fig.xaxis.axis_label="insert x axis here" "

**Comment by QuentinDumont** [comment]
This is actually already possible in bokeh : 
fig.xaxis.axis_label = 'Name'

Not sure about Pyqtgraph though.
