### ISSUE TITLE
Interactive Plot has a few other options in IDL that we don't have

### ISSUE THREAD

**Issue by bryan-harter** [MAVENSDC/PyTplot#64]
Feel free to break this issue up further

-Option to set xlog/ylog for interactive plots (right now I think its defaulted to use whatever ylog/zlog were set to in the original variable)

-Option to make the crosshair legend/crosshairs an optional thing.

-Option to set xrange/yrange

-Option to save a png from the window

**Comment by jibarnum** [comment]
Added in those options!
