### ISSUE TITLE
Create an interactive plot tool for spectrograms

### ISSUE THREAD

**Issue by esalvolucas** [MAVENSDC/PyTplot#7]
This should utilize the HoverTime class in the previous ticket.

Basically, make a new script that, when run, will pop up a completely new window with a simple 1D plot. That plot will change depending on what time the user is hovering over. Specifically, for specplots, it will take the time you're hovered over plot the spec_bins vs the data values at that specific time.

**Comment by jibarnum** [comment]
Fixed this a bit ago, just forgot to close the ticket!
